(uiop:define-package cloveleaf
  (:use #:cl #:com.inuoe.jzon)
  (:export #:*smufl-specification-version*
	   #:font
	   #:font-name
	   #:font-version
	   #:font-pathname
	   #:font-glyph-hash
	   #:font-engraving-defaults
	   #:font-design-size
	   #:font-size-range
	   #:font-classes
	   #:font-ranges
	   #:font-sets
	   #:text-font
	   #:metadata-font
	   #:font-metadata
	   #:glyph
	   #:glyph-name
	   #:glyph-code-point
	   #:glyph-code
	   #:glyph-character
	   #:glyph-description
	   #:glyph-alternates
	   #:glyph-alternate-for
	   #:glyph-advanced-width
	   #:glyph-anchors
	   #:glyph-bounding-boxes
	   #:ligature-glyph
	   #:glyph-ligature-component-glyphs
	   #:glyphp
	   #:load-glyphs
	   #:+cloveleaf-glyphnames-filename+
	   #:+cloveleaf-classes-filename+
	   #:+cloveleaf-ranges-filename+
	   #:*cloveleaf-source-directory-pathname*
	   #:read-glyphnames
	   #:code-codepoint
	   #:classes
	   #:classes-name
	   #:classes-glyphs
	   #:ranges
	   #:ranges-name
	   #:ranges-description
	   #:ranges-end
	   #:ranges-start
	   #:ranges-glyphs
	   #:read-smufl-data))
